#############################################################################
# Makefile for building: Gameboy.app/Contents/MacOS/Gameboy
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  Gameboy.pro
# Template: app
# Command: /Users/Jc_tecklenburg/Qt/5.3/clang_64/bin/qmake -o Makefile Gameboy.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/macx-clang -I. -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/Jc_tecklenburg/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gameboy.cpp \
		Z80.cpp \
		screen.cpp moc_screen.cpp
OBJECTS       = gameboy.o \
		Z80.o \
		screen.o \
		moc_screen.o
DIST          = /Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/qdevice.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/unix.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/mac.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/macx.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/clang.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/qconfig.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/resources.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/moc.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/uic.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/lex.prf \
		gameboy.pro gameboy.cpp \
		Z80.cpp \
		screen.cpp
QMAKE_TARGET  = Gameboy
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Gameboy.app/Contents/MacOS/Gameboy

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Gameboy.app/Contents/PkgInfo Gameboy.app/Contents/Resources/empty.lproj Gameboy.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d Gameboy.app/Contents/MacOS/ || mkdir -p Gameboy.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gameboy.pro /Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf /Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/qdevice.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/unix.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/mac.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/macx.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/clang.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/qconfig.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/resources.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/moc.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/uic.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/lex.prf \
		gameboy.pro \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Gameboy.pro
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/qdevice.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/device_config.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/unix.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/mac.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/macx.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/clang.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/qconfig.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/default_post.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/qt.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/resources.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/moc.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/uic.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/yacc.prf:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/features/lex.prf:
gameboy.pro:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Gameboy.pro

qmake_all: FORCE

Gameboy.app/Contents/PkgInfo: 
	@test -d Gameboy.app/Contents || mkdir -p Gameboy.app/Contents
	@$(DEL_FILE) Gameboy.app/Contents/PkgInfo
	@echo "APPL????" >Gameboy.app/Contents/PkgInfo
Gameboy.app/Contents/Resources/empty.lproj: 
	@test -d Gameboy.app/Contents/Resources || mkdir -p Gameboy.app/Contents/Resources
	@touch Gameboy.app/Contents/Resources/empty.lproj
	
Gameboy.app/Contents/Info.plist: 
	@test -d Gameboy.app/Contents || mkdir -p Gameboy.app/Contents
	@$(DEL_FILE) Gameboy.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,JCT.Gameboy,g" -e "s,@EXECUTABLE@,Gameboy,g" -e "s,@TYPEINFO@,????,g" /Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >Gameboy.app/Contents/Info.plist
dist: 
	@test -d .tmp/Gameboy1.0.0 || mkdir -p .tmp/Gameboy1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/Gameboy1.0.0/ && $(COPY_FILE) --parents Z80.h screen.h .tmp/Gameboy1.0.0/ && $(COPY_FILE) --parents gameboy.cpp Z80.cpp screen.cpp .tmp/Gameboy1.0.0/ && (cd `dirname .tmp/Gameboy1.0.0` && $(TAR) Gameboy1.0.0.tar Gameboy1.0.0 && $(COMPRESS) Gameboy1.0.0.tar) && $(MOVE) `dirname .tmp/Gameboy1.0.0`/Gameboy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Gameboy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Gameboy.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_screen.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_screen.cpp
moc_screen.cpp: /Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsItem \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h \
		screen.h
	/Users/Jc_tecklenburg/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/macx-clang -I'/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim and Mod/Gameboy' -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib screen.h -o moc_screen.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

gameboy.o: gameboy.cpp screen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsItem \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h \
		Z80.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QtGui \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessible.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessiblebridge.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleobject.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbitmap.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qicon.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengine.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengineplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimageiohandler.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagewriter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpicture.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpictureformatplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmapcache.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcursor.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdrag.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericpluginfactory.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qinputmethod.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qkeysequence.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qoffscreensurface.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglcontext.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpalette.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qscreen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsessionmanager.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstylehints.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurface.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtouchdevice.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindow.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindowdefs.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericmatrix.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qquaternion.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengl.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglbuffer.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglframebufferobject.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpaintdevice.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpixeltransferoptions.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglshaderprogram.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltexture.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltimerquery.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglversionfunctions.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglvertexarrayobject.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbackingstore.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbrush.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagedpaintdevice.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagelayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagesize.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintdevice.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintengine.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainterpath.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpdfwriter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpolygon.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qregion.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrgb.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtransform.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qabstracttextdocumentlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontdatabase.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontinfo.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qglyphrun.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrawfont.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstatictext.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextcursor.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocument.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentfragment.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentwriter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextformat.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlist.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextobject.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextoption.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtexttable.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdesktopservices.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvalidator.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtguiversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameboy.o gameboy.cpp

Z80.o: Z80.cpp Z80.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Z80.o Z80.cpp

screen.o: screen.cpp /Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QtGui \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessible.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessiblebridge.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleobject.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbitmap.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qicon.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengine.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengineplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimageiohandler.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagewriter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpicture.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpictureformatplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmapcache.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcursor.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdrag.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericpluginfactory.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qinputmethod.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qkeysequence.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qoffscreensurface.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglcontext.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpalette.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qscreen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsessionmanager.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstylehints.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurface.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtouchdevice.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindow.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindowdefs.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericmatrix.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qquaternion.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengl.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglbuffer.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglframebufferobject.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpaintdevice.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpixeltransferoptions.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglshaderprogram.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltexture.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltimerquery.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglversionfunctions.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglvertexarrayobject.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbackingstore.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbrush.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagedpaintdevice.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagelayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagesize.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintdevice.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintengine.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainterpath.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpdfwriter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpolygon.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qregion.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrgb.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtransform.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qabstracttextdocumentlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontdatabase.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontinfo.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qglyphrun.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrawfont.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstatictext.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextcursor.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocument.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentfragment.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentwriter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextformat.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlist.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextobject.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextoption.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtexttable.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdesktopservices.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvalidator.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtguiversion.h \
		screen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsItem \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGraphicsView \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screen.o screen.cpp

moc_screen.o: moc_screen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screen.o moc_screen.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/gameboy || mkdir -p $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/gameboy
	$(DEL_FILE) -r "$(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim and Mod/Gameboy/gameboy/Gameboy.app"
	
	-$(INSTALL_DIR) "Gameboy.app" "$(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim and Mod/Gameboy/gameboy/Gameboy.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim and Mod/Gameboy/gameboy/Gameboy.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim and Mod/Gameboy/gameboy/ 


install_sources: first FORCE
	@test -d $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/. || mkdir -p $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/.
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/gameboy.cpp $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/Z80.cpp $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/screen.cpp $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/Z80.h $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/screen.h $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/gameboy.pro $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./

uninstall_sources: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./gameboy.pro
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./screen.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./Z80.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./screen.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./Z80.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim\ and\ Mod/Gameboy/./gameboy.cpp
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/Jc_tecklenburg/Documents/School/AU_Senior_Fall/Sim and Mod/Gameboy/./ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

